import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
]

[shell]
program = "/bin/zsh"
# args = ["-l"]

[font]
size = 14.0

[font.normal]
family = "Lilex Nerd Font"

[window]
startup_mode = "Maximized"

[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" },
]
